# Generated by Django 6.0.2 on 2026-03-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('etnia', models.CharField(choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Não Declarada', 'Não Declarada')], max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('foto_path', models.ImageField(blank=True, null=True, upload_to='fotos_alunos/')),
                ('nacionalidade', models.CharField(choices=[('Brasileira', 'Brasileira'), ('Estrangeira', 'Estrangeira')], max_length=50)),
                ('naturalidade', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Outro', 'Outro')], max_length=20)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('zona_residencial', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=20)),
                ('possui_deficiencia', models.BooleanField()),
                ('qual_deficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_de_ensino', models.CharField(choices=[('Sem escolaridade', 'Sem escolaridade'), ('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo')], max_length=50)),
                ('tipo_instituicao', models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('atividades', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Presencial', 'Presencial'), ('EAD', 'EAD'), ('Híbrido', 'Híbrido')], max_length=50)),
                ('data_de_criação', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=50)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('cpf_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_curso', to='crcacad.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.IntegerField()),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('situação_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado')], max_length=50)),
                ('competencia', models.CharField(help_text='Formato: MM/AAAA', max_length=7)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='crcacad.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero_da_turma', models.IntegerField(primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=50)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('descricao', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='crcacad.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Professor_Turma_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_turma_disciplina', to='crcacad.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_turma_disciplina', to='crcacad.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_turma_disciplina', to='crcacad.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_matricula', models.DateField(auto_now_add=True)),
                ('data_do_desligamento', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='crcacad.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='crcacad.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atividade', models.IntegerField()),
                ('data_da_atividade', models.DateField()),
                ('presenca', models.BooleanField(help_text='Presente = Marcado | Ausente = Desmarcado')),
                ('cpf_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='crcacad.aluno')),
                ('nome_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='crcacad.disciplina')),
                ('numero_da_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='crcacad.turma')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=100)),
                ('data_da_atividade', models.DateField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cpf_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_aluno', to='crcacad.aluno')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_aluno', to='crcacad.atividades')),
                ('numero_da_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_aluno', to='crcacad.turma')),
            ],
        ),
    ]
